from array import array
intarr=array('b',[1,2,3,4,5])
print("Array before remove:",intarr)
intarr.insert(0,0)
print("Array after adđing item",intarr)
intarr.insert(6,6)
print("Array after adđing item2",intarr)
intarr.insert(7,7)
print("Array after adđing item3",intarr)
intarr.insert(8,8)
print("Array after adđing item4",intarr)
intarr.insert(9,9)
print("Array after adđing item2",intarr)
intarr.insert(10,10)
print("Array after adđing item2",intarr,"end")

